Some new actions! :)
EddieHubCommunity/gh-action-community pull request #56
Opened 2020-10-01 17:59 UTC by tallguyjenks

2020-10-01 22:29 UTC, eddiejaoude commented
Oh awesome! I will have a look through later on and have a play, thank you @tallguyjenks - the YouTube one definitely looks super interest 💪

2020-10-01 22:43 UTC, tallguyjenks commented
@eddiejaoude if you want to see it live I have the article, youtube, and GH activity all on my profile repo https://github.com/tallguyjenks/tallguyjenks

2020-10-02 08:18 UTC, eddiejaoude commented
Thanks @tallguyjenks 👍

2020-12-05 21:59 UTC, eddiejaoude commented
Stalebot lets keep this for now please 🤓

2020-12-11 18:21 UTC, dumbcoder7 approved these changes

2020-12-21 07:27 UTC, eddiejaoude commented
Not sure we want all these changes just yet. We can bring them in as we use them

2021-06-26 07:26 UTC, tallguyjenks commented
@eddiejaoude still blocked? lol i have a few more actions too now there's so many good ones

2021-06-26 07:44 UTC, eddiejaoude commented
hey @tallguyjenks I am blocked on other stuff and this one is slowly moving down my list 😢 . Oh feel free to append the new actions to this PR?

2021-11-21 05:14 UTC, krishguptadev commented
Since this PR has not been updated/discussed in a while, I am curious why didn't Stale bot interfere.

2021-11-21 05:15 UTC, krishguptadev commented on .github/release-drafter.yml
> +name-template: "$RESOLVED_VERSION"
We would rather prefer to use this action [here](https://github.com/EddieHubCommunity/LinkFree/blob/main/.github/workflows/release.yml)

2021-11-21 05:16 UTC, krishguptadev commented on .github/workflows/articles.yml
> +name: <NAME> on Medium
Why do we need this? We don not have a blog that supports RSS for now, and if it were, I definitely wouldn't add them to a Action's github readme

2021-11-21 05:16 UTC, krishguptadev commented on .github/workflows/release-drafter.yml
> +name: Release Drafter
https://github.com/EddieHubCommunity/gh-action-community/pull/56/files#r753748836

2021-11-21 05:17 UTC, krishguptadev requested changes

2021-11-21 05:17 UTC, krishguptadev commented on .github/workflows/update-readme.yml
> +name: Update README
Why would we need to add someone's github activity to our Readme?

2021-11-21 05:17 UTC, krishguptadev commented on .github/workflows/youtube-workflow.yml
> +name: Latest YouTube Videos
Also, why would we wanna add youtube videos on the readme of a github action

2021-11-21 05:19 UTC, krishguptadev commented
@tallguyjenks From the PR pattern I think you've made the PR to the wrong repo, this repo is about GitHub Actions and you've added stuff relevant to a github profile readme.

@eddiejaoude I think this PR can be closed 🙂

2021-11-21 14:48 UTC, tallguyjenks commented
they were just example actions for others to grab and use, not something I meant to actually run on the repo. by itself, the things affecting the readme wouldn't function without the right HTML comments placed in the readme anyhow.

2021-11-21 14:56 UTC, krishguptadev commented
> they were just example actions for others to grab and use, not something I meant to actually run on the repo. by itself, the things affecting the readme wouldn't function without the right HTML comments placed in the readme anyhow.

but they shouldn't be in .github/workflows any ways 😓

2022-05-24 05:12 UTC, closed without merging